### ISSUE TITLE
Change of API in Open3D, use release v0.1.1

### ISSUE THREAD

**Issue by pronif** [IntelVCL/TanksAndTemples#10]
Hi,

The evaluation scripts don't work with the newest version of Open3D. There have been some changes in API (mainly the python module is now called open3d and not anymore py3d).

It is sufficient to checkout the release v0.1.1 to have the script work. You may want to update the readme :)

**Comment by syncle** [comment]
Thanks @pronif! I will update texts in setup.py, so that newest open3d version can be used for TanksAndTemples evaluation scripts.
