### ISSUE TITLE
Outdated get_colmap_reconstruction.sh

### ISSUE THREAD

**Issue by GrumpyZhou** [IntelVCL/TanksAndTemples#18]
Hi,
Just fyi.
It seems there are some name changes in colmap. So the code in get_colmap_reconstruction.sh needs to be updated at least for my environment, linux ubuntu version:

colmap dense_stereo  now becomes patch_match_stereo
colmap dense_fuser  now becomes stereo_fusion

**Comment by arknapit** [comment]
Thanks for noticing. Should be good now.
